### PR TITLE
Refactor sound source manager to make it more efficient

### PR DESCRIPTION
**Pull request by aki-cat**
I thought this PR would solve #76 but it doesn't. But it does make lagging much better (for me) and it assures that memory usage for audio sources is constant at all times. I imagine the lag I've been experiencing has been the slam lib constantly creating new audio sources during gameplay. This PR loads all sources in loading time and uses constant amounts of buffers for each source.

This PR also removes `slam.lua` as it become unnecessary. I hope that's okay?
Tell me what y'all think

### CODE REVIEW

**Comment by rilifon** [comment]
Why did you close it?? D: 
Actualyl I think is my fault for forgetting about this PR ><
Do you think it makes the game faster? Can you test it with the current dev?

**Comment by aki-cat** [comment]
I thought it wasn't relevant anymore. It doesn't make the game faaaaaaster, but it makes the amount of memory allocated for sound always constant and predictable. And perhaps it makes the code a bit easier to enhance upon.

You want me to reopen it?

**Comment by rilifon** [comment]
Sure! One concern is some sfx not playing due to buffer capacity limit, but we can easily increased it.

I made a few adjustments a few weeks back where I think I fixed some problems with fades on bgm, to properly consider the profile preference of bgm sounds. My other concern is you check your fade functions to make sure they use this values appropriately (This cant be possible right now, but in the future, if the player is changing the volume settings and music is between a fade, it should work as expected).

Those minor issues considered, I actually prefer to use your library instead of slam's

**Comment by aki-cat** [comment]
Are the volume settings you mentioned already merged? If so I can fix the code and rebase it accordingly and reopen the PR.

**Comment by rilifon** [comment]
@OrenjiAkira after spending the day profiling, I came to the conclusion the game has lag spikes due to inneficient audio playing, so I'm confident your PR will fix this. Can you reopen and rebase with dev so we can test it?

**Pull request closed without merging**
